### ISSUE TITLE
Add java classes from protoc with release

### ISSUE THREAD

**Issue by dertroglodyt** [djungelorm/krpc#100]
As I understand it takes only a run of "protoc" to add the java classes in a jar file. As I don't have the time to get into c#/python/protocol buffers and / or installing any / all of those but still would like to give it a try in java: Could you pretty pretty please go the extra mile for the java classes?
In any case, thanks for your work.

**Comment by djungelorm** [comment]
Of course! Here is the KRPC.java file that protoc generates from KRPC.proto:
https://gist.github.com/djungelorm/7ee51aaabafbe6172f2d

Couple that with Google's java protobuf library, and you should be good to go.
