### ISSUE TITLE
Document the communication protocol for streams

### ISSUE THREAD

**Issue by djungelorm** [djungelorm/krpc#112]
Currently blank on the documentation website...

**Comment by thesamprice** [comment]
Would you consider using the CCSDS protocol for sending / receiving commands / telemetry?
See http://public.ccsds.org/publications/archive/133x0b1c2.pdf
page 4-2

**Comment by djungelorm** [comment]
Possibly. I'd certainly like to make the underlying communication protocol moddable - so that you can hook in whatever funky protocol you like. I've made a dedicated issue for this here: #123
