### ISSUE TITLE
get_Vessels return values

### ISSUE THREAD

**Issue by finger563** [djungelorm/krpc#115]
get_Vessels (according to the code) seems like it should return a List of Vessels (i.e. objects containing name and other values) but instead it only returns a list uint64 ids.  Perhaps instead of IList<Vessel> it can be IDictionary<Vessel,string>?  or something more informative to cut down on network traffic; right now if i want to build a map of ID->vessel name I need to make a get_Vessels() call and then run Vessel_get_Name() on each one separately.

**Comment by djungelorm** [comment]
It returns a list of uint64 because that is how objects are represented by kRPC on the client side. The uint64 is the id number of the object stored on the server.

Returning a dictionary mapping names to vessels would be a bit problematic as names aren't necessarily unique. Although this functionality could be added, and if multiple vessels with the same name exist, the dictionary maps that name to just one of the vessels (arbitrarily chosen).

**Comment by finger563** [comment]
What I was thinking is returning a unique map from id to name. That at least reduces the network traffic required.  And the user can decide what to do about non unique names. 

William Emfinger 
Graduate research assistant 
Vanderbilt university institute for software integrated systems 
16th avenue s Nashville TN 37212

**Comment by djungelorm** [comment]
Ah OK, I see. Out of interest, why are you needing a mapping from vessel object IDs to names?

**Comment by finger563** [comment]
For when we have the ability to simultaneously control multiple vessels, we will have unique vessel names and we want specific clients to control specific vessels.  Currently we have 32 vessels (satellites for now, but also going to include rovers and UAVs) which are each controlled by separate hardware (for now we are using BeagleBone Blacks running debian and the robot operating system (ROS) middleware).

**Comment by djungelorm** [comment]
Generating this dictionary client side is pretty simple (snippet below) and only costs one RPC per vessel (which is very cheap). I'd prefer to leave a function such as "GetVesselsWithName" out of the API, as it's rather specific, and one could argue that we should then also add "GetVesselsWithType", GetVesselsWithSituation" etc. leading to API bloat.

```python
vessel_name_map = dict((v, v.name) for v in conn.space_center.vessels)
```
