### ISSUE TITLE
Isp returns 0.0 when thrust is 0.

### ISSUE THREAD

**Issue by shyadow** [djungelorm/krpc#117]
When using vessel.specific_impulse (or vessel.vacuum_specific_impulse / vessel.kerbin_sea_level_specific_impulse) and the thrust is 0, you get the return value 0.0. 

When right clicking on the engine in-game it still gives the correct specific impulse.

It caused a problem when I was trying out the launch into orbit script that's on the docs and it was calculating the burn time:

    F = vessel.thrust
    Isp = vessel.specific_impulse * 9.82
    m0 = vessel.mass
    m1 = m0 / math.exp(delta_v/Isp)
    flow_rate = F / Isp
    burn_time = (m0 - m1) / flow_rate

This causes a ZeroDivisionError, because the thrust at the time of calculating this was 0, and therefore the vessel.specific_impulse returned 0.0.

**Comment by djungelorm** [comment]
Bug is due to using current engine thrust instead of maximum engine thrust when computing the combined specific impulse of all the vessel's engines.
