### ISSUE TITLE
No speed reporting

### ISSUE THREAD

**Issue by kbytesys** [djungelorm/krpc#126]
The python library doesn't report any speed (speed, vector, horizontal_speed, vertical_speed)

Look this example from a debug session.

In this case I've started the program when the rocket was already launched, but I was unable to manage to get speed also with "add_stream" function too.

I'm using python 3.4 and krpc 0.1.8 library
![speed](https://cloud.githubusercontent.com/assets/1544245/7572644/11669b16-f820-11e4-92fa-cacf4394a09f.png)

**Comment by kbytesys** [comment]
Ignore this bug report. I forgot the reference frame :P

**Comment by djungelorm** [comment]
A common mistake and easily done!!
