### ISSUE TITLE
krpc.schema missing from sources

### ISSUE THREAD

**Issue by kbytesys** [djungelorm/krpc#127]
Hi! I'm unable to build the python library because krpc.schema is missing. If you download this release file https://pypi.python.org/packages/source/k/krpc/krpc-0.1.8.tar.gz you will find the folder there, but it isn't in this repository!

**Comment by djungelorm** [comment]
The file ```python/krpc/schema/KRPC.py``` is generated from ```src/kRPC/Schema/KRPC.proto```
As it's a generated file it's not stored in source control.

This file can be generated using the Makefile by running ```make protobuf```
Or you could just copy the generated file from the release archive.

More details here: http://djungelorm.github.io/krpc/docs/compiling.html#the-python-client-library

**Comment by kbytesys** [comment]
Ok. Fixed thank you :P
