### ISSUE TITLE
Server Performance issue

### ISSUE THREAD

**Issue by kbytesys** [djungelorm/krpc#129]
I'm your nightmare... I know :P But this is my last bug report I promise! :smile_cat: 

I noticed some small freezes and fps drops every second.

![perf2](https://cloud.githubusercontent.com/assets/1544245/7598524/1a1de350-f8fb-11e4-891f-ddf7e74c8535.png)

As you can see, fps drops to 25.0 regularly. There are no connections to the krpc server, the issue isn't triggered by clients activity.

If you stop the server, ksp works fine and smooth.

If you use the scansat mod, you will find another strange behaviour. When you update the scan from the UI or from the IVA with the krpc server started, the fps will drop to 25.0 and the sat scan screen will refresh slower.

![perf3](https://cloud.githubusercontent.com/assets/1544245/7598591/b42f0f00-f8fb-11e4-8c0d-c15d6f97d163.png)

I've tried to remove scansat and other potentially offending mods, but without any significant differences.

I would like to help you to debug/improve the performance, just let me know how I can help you.

**Comment by djungelorm** [comment]
Off the top of my head I can't think why this could be happening - as far as I'm aware the server doesn't intentionally run anything at 1 second intervals!

If you want to have a go at debugging it that'd be great :) The entry point to the server code is here:
https://github.com/djungelorm/krpc/blob/master/src/kRPC/KRPCServer.cs#L217
KRPCServer.Update is run every physics tick.

Hopefully fixing the first problem will resolve the second scansat problem, as they sound related.

**Comment by kbytesys** [comment]
I will create my build env in the next days. How logging/debug works in ksp (just point me to some doc please)?

I've also found the reason of the magic number 25.0 (fps): kerbal execute at least 25 physics ticks per second. If the fps drops to that value, it means that mods overload the physics update cycle. 

In the RPCServerUpdate() function you will cycle for 10ms also if there are no active requests. I will try to drop that do-while, because if there are no requests or the update or the execution is yielded, I think is better to wait the next update.

**Comment by djungelorm** [comment]
I do all my development on Linux. I debug by just printing things out to KSPs log file using ```System.Console.WriteLine("...")```. And I run KSP using the [Makefile](https://github.com/djungelorm/krpc/blob/master/Makefile#L236), by running ```make ksp``` from a terminal. It builds and installs the mod into KSP, runs KSP, and then pipes KSPs log file to the terminal.

If you want to look at it manually, the KSP log file is stored in the following location on Linux:
```~/.config/unity3d/Squad/Kerbal Space Program/Player.log```
Or in the following location on Windows:
```<path-to-ksp>/KSP_Data/output_log.txt```

There's also this: http://forum.kerbalspaceprogram.com/threads/73586-Profiling-Debugging-Support-For-KSP-Plugins-%2822-Aug-Unity-4-5%29 ...but I've not tried it out yet.

**Comment by djungelorm** [comment]
The reason I added that 10ms wait was to increase the rate at which RPCs can be executed.

RPCs are sent by a client one after another - the client must wait for one RPC to complete before another can be sent to the server. Without the 10ms wait, only one RPC can be executed per physics update. This imposes a limit on the RPC execution rate of 25 RPCs per second. With the 10ms wait, the server can execute multiple RPCs per update, as after the first RPC it waits for the next one.

A possible fix might be to only perform the 10ms wait after the first RPC has executed. So if the server is idle it'll never wait. Also 10ms was chosen rather arbitrarily, it would probably be better to have some sort of adaptively chosen wait time, possibly based on the current FPS - i.e. if the FPS is low, reduce the wait time.

**Comment by kbytesys** [comment]
I didn't understand why you have to call rpcServer.Update() and streamServer.Update() into the do-while. 
You get the continuations of a single client on each call???

Btw I've made a simple test in my repo executing many clients with success, but I need to do more test.

Please take a look to this commit: 

https://github.com/kbytesys/krpc/commit/be4e1ac19fb26092b038f4498d9e401a13df322e

**Comment by djungelorm** [comment]
rpcServer.Update(), streamServer.Update() and PollRequests are called in the do-while so that new RPCs sent by clients during the (up to) 10ms execution period are received and processed.

I'm at work, so can't run your code, but it looks like it will only ever execute up to one RPC from each client on each physics tick? We want it to be able to execute multiple RPCs from a single client, up until the 10ms time limit - but avoid waiting 10ms if there is nothing to execute. Maybe just wait 1ms to see if anything comes in, and if not return.

**Comment by kbytesys** [comment]
Ok, I've understand now. The real problem is the idle cycle. I will made some changes and let you know later.

**Comment by djungelorm** [comment]
Looks good! I think we could improve the ```Thread.Sleep(waitTime)``` by replacing it with a loop that keeps checking if there are new RPCs, for up to waitTime milliseconds. For example:

```python
Stopwatch pollTimer = Stopwatch.StartNew ();
while (pollTimer.elapsedMilliseconds < waitTime && continuations.Count == 0) {
    rpcServer.Update ();
    streamServer.Update ();
    PollRequests (yieldedContinuations);
}
```
and then move the update calls on lines 242 to 244 out of the do loop.

That way, the server will only wait as long as necessary to receive new RPCs, and won't wait longer than 1ms.

**Comment by djungelorm** [comment]
Looks like my use of FixedUpdate over Update might be misguided. It doesn't actually run at a fixed rate as I assumed... FixedUpdate is periodically run a bunch of times, to fake a fixed rate for physics simulation. So even with the changes in #131 there are brief drops to 25 FPS when FixedUpdate gets run repeatedly, and the main server loops does lots of work. I'm testing out using plain old Update instead.

http://forum.unity3d.com/threads/the-truth-about-fixedupdate.231637/

**Comment by kbytesys** [comment]
The update cycle is called often than the FixedUpdate, I suggest you to try the one rcp call for each client algoritm because sleeps into that cycle can tear down the whole performance of the game. You can also try to put the streamserver into the FixedUpdate and the rpcserver into Update.

Unity3d have also threads and coroutines, but you have to manage a thread safe way to handle requests and game data. Btw they are a bit hard to use, so the Update() solution are welcome if it works :smiley_cat:

**Comment by djungelorm** [comment]
Ah yes, you're right. Probably best to leave it in FixedUpdate, but I'll have a play around anyway. I want to avoid threads and coroutines, as that would open a rather large can of worms!

**Comment by djungelorm** [comment]
I've pushed some changes to the feature/server-performance branch that improve this stuff further. https://github.com/djungelorm/krpc/compare/feature/server-performance

 * I've cleaned up the main server loop and renamed things a bit - and changed the timers to use microseconds to allow finer grained control.
 * Added all the timer parameters to the server window so they can be adjusted. I plan to move these to an 'advanced settings' tab.
 * Added a button to enable "adaptive rate control". In this mode, the server automatically chooses a value for the maximum execution time for the loop. It basically increases the max exec time until it starts to see the framerate drop below 60. This provides a nice way to get smooth framerates and also maximise the RPC execution rate.
 * Added a load of statistics tracking so you can see what the server performance is like. These are currently shown in the main server window, but I will move them to some sort of 'debug' or 'performance' window.

**Comment by kbytesys** [comment]
Great! I'm a little busy atm, but I will compile and test krpc this weekend.
