### ISSUE TITLE
Location of python source code

### ISSUE THREAD

**Issue by ivandmitrievsky** [djungelorm/krpc#132]
I've searched your repo, but couldn't find implementation of python SpaceCenter API.
I mean, where `class CelestialBody` is actually defined? I would appreciate if you clarify this :blush:

**Comment by djungelorm** [comment]
The classes are dynamically created when the python client connects to the server, so they aren't hard coded anywhere.

**Comment by ivandmitrievsky** [comment]
If I want to implement a client library in my favorite language should I learn C# and generate library code dynamically as you do for Python, or there is a way to just implement a standalone client that communicates with KSP?

**Comment by djungelorm** [comment]
C# code is not required to implement a client library. The python client is written purely python ;) The same should be possible for <insert favourite language here>.

The way the python client dynamically creates all the classes is that it invokes an RPC called GetServices to get a list of all the RPCs provided by the server (details here http://djungelorm.github.io/krpc/docs/communication-protocol.html#service-description-message). This provides the python client with all the information necessary to dynamically create all the python classes.

The bit of code in the python client that does this dynamic creation is here: https://github.com/djungelorm/krpc/blob/master/python/krpc/service.py

This project https://github.com/Vivero/KNav takes a different approach. It uses a program (written in C++) to generate the source code for a C++ client, using the information provided by GetServices.

**Comment by ivandmitrievsky** [comment]
Now I see, thanks! :blush: 
And hard coding is a bad thing, because provided services can change through time?

**Comment by djungelorm** [comment]
Yeah hard coding is best avoided! The server supports 3rd party services, so the services provided by two different servers may not match. There may also be differences between different versions of, say, the SpaceCenter service. So the python client is dynamic so that you don't need to modify the client every time the server changes. Keeps them nicely decoupled :)

**Comment by ivandmitrievsky** [comment]
Yeah, you're right :relieved:  Thanks for your help! :star:
