### ISSUE TITLE
RPCs to set warp rates

### ISSUE THREAD

**Issue by djungelorm** [djungelorm/krpc#134]
Add RPCs to manually set the warp rate, for both physics warp and time warp.

**Comment by baloan** [comment]
The use case for warp factors is to warp to a distance from a body (either from farther away or from closer). This is used
1. to stop warping when changing soi and to reduce physics errors (this might actually no longer be a problem with KSP 1.0.2)
2. to stop warping when approaching a planet's atmosphere. Warping should stop at a radius of 669km from Kerbin.
I have a method ```warp_dist()``` which uses the warp factor to accomplish that.
