### ISSUE TITLE
[bug] warp_to not implemented

### ISSUE THREAD

**Issue by baloan** [djungelorm/krpc#137]
When warping I get
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\Andreas\workspace\sandbox\src\toolkit\warp.py", line 29, in warpday
    SC.warp_to(SC.ut + wt)
  File "<string>", line 1, in <lambda>
  File "C:\Apps\Python34\lib\site-packages\krpc\client.py", line 122, in _invoke
    raise RPCError(response.error)
krpc.error.RPCError: The requested feature is not implemented.
```
I am calling
```
conn.space_center.warp_to(2331906.322305925)
```

**Comment by djungelorm** [comment]
Ah, are you in an atmosphere? Looks like physics warp hasn't been implemented.

**Comment by baloan** [comment]
Yes, I am. I want to wait for sunrise on the launchpad. Makes nicer ascents when the craft is lit. Will also be required when timing ascents for docking.

**Comment by djungelorm** [comment]
OK cool. I hadn't considered the case where rails warp is available whilst in an atmosphere. warp_to will need to be modified to consider this use case.

**Comment by baloan** [comment]
Rails warp (all 7 levels) is available while the craft is on the launchpad. I am not sure what the situation is for rovers and landers sitting idle on a body.
```
SC.active_vessel.situation
<VesselSituation.pre_launch: 5>
```
