### ISSUE TITLE
KRPC Interface Generator

### ISSUE THREAD

**Issue by pranav-srinivas-kumar** [djungelorm/krpc#142]
Hey! I've created a simple KRPC interface generator to generate function declarations & definitions for "procedures" on all services obtained from KSP. This has proved useful for my work and may be of interest to you. 

KRPCI Generator
------------------------
https://github.com/finger563/rosmod/tree/master/code/rosmod_v3/tests/testKRPC/krpci

* **krpci_generated.cpp** and **krpci.hpp** are completely generated from Cheetah templates in **templates/*.tmpl**
* Use **krpci_generator.py** to regenerate. 
* To test, you can use **krpci_test.cpp** and the **Makefile**

Thanks,
Pranav

**Comment by djungelorm** [comment]
Cool thanks, I'll check it out!

**Comment by finger563** [comment]
:)

**Comment by djungelorm** [comment]
I get:
```
Traceback (most recent call last):
  File "krpci_generator.py", line 27, in <module>
    from krpci_hpp import *
ImportError: No module named krpci_hpp
```
when trying to run krpci_generator.py

I can't find krpci_hpp.py anywhere. Did you forget to commit a file?

**Comment by finger563** [comment]
That file is generated from ./templates/krpci_hpp.tmpl.  Further up the error stack you should see a cheetah error I believe.  You need to have cheetah installed.  You can find the cheetah source we use (and install from) here:

[rosmod external sources folder](https://github.com/finger563/rosmod/tree/master/code/rosmod_v3/ext)

and you can use the install script here:

[external sources install script](https://github.com/finger563/rosmod/blob/master/code/rosmod_v3/setup.py)

to install cheetah.  Do note that it will install a few other packages that we require for our GUI/Tool (ROSMOD) to work.  So if you only want cheetah, you can just decompress and run its installer manually.

**Comment by pranav-srinivas-kumar** [comment]
Hey! So the templates folder has 2 .tmpl files. These are Cheetah templates that need to be compiled by the Cheetah Templating Engine. The usual workflow is to generate template-specific python files using the engine and then use the template classes. 

How its done
------------------
* We have krpci_hpp.tmpl (and other similar templates) in templates/*
* We compile it with cheetah (done in the krpci_generator.py script)
* This generates krpci_hpp.py in templates/*
* We have not committed this file since it is generated each time krpci_generator.py is run
* This is similarly true for all tmpl files in templates/*
* Once compiled, they can be imported as modules 
* **Since this compilation is failing for you (I imagine since you don't have Cheetah), the import is giving you an error**

Fix to your problem
---------------------------
* Install Cheetah Templating Engine
* Download from: https://pypi.python.org/pypi/Cheetah/2.4.4
* Extract this Cheetah-2.4.4.tar.gz
* cd Cheetah-2.4.4
* sudo python setup.py install

Other Assumptions
--------------------------
* We expect KSP & kRPC server to be running
* We expect an active vessel in flight (in focus, in the game)
* The script fetches all the services & procedures using the KSP interface and generates the API we need.

**Comment by djungelorm** [comment]
Thanks for the info. I've got it working :)

The problem was that I installed Cheetah from Ubuntu's apt repositories, and the path to the binary is /usr/bin/cheetah, not /usr/local/bin/cheetah. It works now that I've changed the path in the script.

**Comment by pranav-srinivas-kumar** [comment]
Ah okay! Neat :)

**Comment by pranav-srinivas-kumar** [comment]
KRPCI Code moved to: 
https://github.com/finger563/rosmod/tree/master/src/ksp/testKRPC/krpci

**Comment by pranav-srinivas-kumar** [comment]
Hey! Here's a short demonstration of the C++ kRPC interface working with KSP:
https://www.youtube.com/watch?v=G15u-AtQVWY

**Comment by djungelorm** [comment]
Very cool! I'm looking into merging your C++ client into the main repo :)

**Comment by finger563** [comment]
Cool!  You're welcome to do that or you can use what we've made:

[krpci repository](https://github.com/pranav-srinivas-kumar/krpci)

Into which we've moved all our c++ client code and interface generator.  We'll be including that repository into our main ROSMOD repository as a submodule.  You're welcome to do the same if that meets your needs :)

**Comment by djungelorm** [comment]
I'm going to keep it in the main repo i think. I also plan to extend it to do things like have kRPC classes/methods/properties look like C++ classes/methods etc.
