### ISSUE TITLE
vessel.thrust doesn't consider fuel status

### ISSUE THREAD

**Issue by DavidEscott** [djungelorm/krpc#146]
vessel.thrust returns the thrust of all active engines even if the engine has no fuel.

If would be nice if engine.has_fuel could be added as an optional argument to this function, so that one could get the actual thrust achieved without having to walk the tree.

**Comment by djungelorm** [comment]
I think Vessel.thrust and Engine.thrust should return 0 if the engine has no fuel, rather than add a parameter as this would make it a method rather than a property. Breaks backwards compatibility... but I still consider the mod a WIP so am not too worried about that.
