### ISSUE TITLE
Flight velocity and Flight speed are always 0

### ISSUE THREAD

**Issue by finger563** [djungelorm/krpc#149]
Because of [this line](https://github.com/djungelorm/krpc/blob/master/src/kRPCSpaceCenter/Services/ReferenceFrame.cs#L434), [this line](https://github.com/djungelorm/krpc/blob/master/src/kRPCSpaceCenter/Services/ReferenceFrame.cs#L323), [this line](https://github.com/djungelorm/krpc/blob/master/src/kRPCSpaceCenter/Services/Flight.cs#L215), and [this line](https://github.com/djungelorm/krpc/blob/master/src/kRPCSpaceCenter/Services/Flight.cs#L38), calculation of velocity (and thus speed) for all flights is incorrect.  All in the end, (worldVelocity - Velocity) ends up being a velocity subtracted from itself.  I've tested this for multiple vessels both on the ground and in the air, and velocity and speed are both returned as 0 always.

**Comment by finger563** [comment]
Note: I tried the fix mentioned [here](https://github.com/djungelorm/krpc/issues/108), but still got zero.

**Comment by djungelorm** [comment]
Could you provide a snippet of python code that demonstrates the problem? And what reference frame are you using to construct the flight class? If it is fixed relative to the vessel then the velocity and speed should be zero.

**Comment by djungelorm** [comment]
Just noticed you marked this as closed...
