### ISSUE TITLE
draw arbitrary vectors

### ISSUE THREAD

**Issue by finger563** [djungelorm/krpc#150]
Please add an API for drawing arbitrary vectors in the game.  E.g. allowing us to display waypoints for autonomous craft as vectors in the game.  These can be drawn on the celestial body reference frame extending from the center of the body, or possibly using some other method (perhaps by giving a reference frame and a displacement?  that way the vector to be drawn may not need to be longer than the radius of the body?)

**Comment by djungelorm** [comment]
I've added SpaceCenter.DrawLine for drawing arbitrary lines.
