### ISSUE TITLE
C++ client

### ISSUE THREAD

**Issue by djungelorm** [djungelorm/krpc#164]
Implement a C++ client, exposing server functionality using full C++ namespaces/classes/methods/fields.

The client in #142 creates a flat list of procedures.

**Comment by djungelorm** [comment]
On branch feature/cpp-client2

**Comment by Outurnate** [comment]
What's the status of this?  Prod ready?

**Comment by djungelorm** [comment]
Pretty much. Changes have been merged into master. No stream support yet though.

**Comment by Outurnate** [comment]
If I need it, I'll implement it.  Thanks!

**Comment by djungelorm** [comment]
Released in 0.1.12
