### ISSUE TITLE
Send stream update only when streamed value changes

### ISSUE THREAD

**Issue by TeWu** [djungelorm/krpc#170]
It looks like a waste of processing time (and bandwidth) to send stream update when streamed value didn't changed. It also looks like adding a simple `if(old_value != new_value){ send_update(...) }` could fix it.

After this improvement, streams would became useful for values that changes very occasionally. For example, at the time `SpaceCenter.active_vessel` method performs RPC every time it is called. But if this method would use value from stream, that is updated only when active vessel changes, it would cause big drop in number performed RPC and big boost to overall performance. It would be especially true in code like:
```python
conn.active_vessel.auto_pilot.target_pitch_and_heading(90,90)
conn.active_vessel.auto_pilot.engage()
conn.active_vessel.control.throttle = 1
...
```

**Comment by djungelorm** [comment]
Nice idea. However, this change will only reduce network overhead. It won't reduce the number of RPCs that need to be run (on the server side), as an RPC needs to be run to see if the return value has changed.
