### ISSUE TITLE
client licensing may want to be more permissive or dual licensed

### ISSUE THREAD

**Issue by coldnebo** [djungelorm/krpc#172]
GPLv3 makes sense for the kRPC server, but might place unintended restrictions on other client implementations. Since the core of the protocol is defined in KRPC.proto, it seems that any clients must be GPLv3 as well, which may limit how they can be deployed.

For example, a Swift or Objective-C IOS client for kRPC under [GPLv3 would be incompatible with Apple App Store deployment](http://apple.stackexchange.com/questions/6109/is-it-possible-to-have-gpl-software-in-the-mac-app-store) even if the source were made freely available.

A MATLAB kRPC client would be a case where the client must link with non-free software (MATLAB) in order to run.  As such it is not GPLv3 compatible unless a [licensing exception is made to link to the non-free program](http://www.gnu.org/licenses/gpl-faq.html#GPLPluginsInNF).

Since the client is useless without the server, it would seem sufficient to keep GPLv3 on the server and perhaps consider a more permissive license for the client protocol (such as Apache2, BSD or MIT).  

Other applications such as mysql use a dual-licensing approach, whereby the mysql client is GPL, however it is also dual-licensed under Oracle such that anyone using the library accepting their terms can link the client libraries into their applications without having to be GPL (i.e. the ruby mysql2 gem is  MIT licensed but links to mysql client libraries under the [FOSS License Exception](https://www.mysql.com/about/legal/licensing/foss-exception/)). 

Github has a resource http://choosealicense.com/licenses/ that describes more about the various licenses and consequences.

**Comment by djungelorm** [comment]
I agree, GPL is not really appropriate. Also possibly not appropriate for the server code, as third party service DLLs have to link against it.

I'm a bit snowed under at the moment but will look at this in more detail when I have time.

**Comment by djungelorm** [comment]
I plan to reorganise the source code into the following directory structure, with the following licenses:

 * ```/server``` - code for kRPC.dll (the core server framework) - LGPL licensed (allows other mods to use it as a library, using the KRPCAttributes interface to add RPCs).
 * ```/service/SpaceCenter``` - code for kRPCSpaceCenter.dll - GPL licensed as it contains some GPL'd autopilot code from MechJeb/RemoteTech etc.
 * ```/service/KerbalAlarmClock``` - code for kRPCKerbalAlarmClock.dll - LGPL
 * ```/service/InfernalRobotics``` - code for kRPCInfernalRobotics.dll - LGPL
 * ```/client/python``` - LGPL
 * ```/client/cpp``` - LGPL
 * ```/client/lua``` - LGPL
 * ```/protobuf```` - the .proto files - MIT licensed, for the reasons argued by the OP

Thoughts?

**Comment by coldnebo** [comment]
Looks good.  The protocol being MIT licensed allows anyone to implement their own clients for communication with your server.

IANAL, but my reading of the GPLv3 faq, the GPL licensed portion is part of a plugin for a non-free main program (KSP) and so needs a [licensing exception](http://www.gnu.org/licenses/gpl-faq.html#GPLPluginsInNF) for that part, but is allowable.  

LGPL is less restrictive and allows the library to be linked to non-free programs, which is fine for a KSP plugin (I'm not sure why MechJeb didn't do this, they seem to be technically in violation of GPL because their plugin links to KSP without indicating a licensing exception for KSP).

**Comment by djungelorm** [comment]
Licenses have been updated in upcoming release 0.1.13
