### ISSUE TITLE
Is it possible to stream variables?

### ISSUE THREAD

**Issue by janismac** [djungelorm/krpc#173]
I use the abort button ingame to tell my script to halt. Can a stream be used here? 

    abort = conn.add_stream(vessel.control.abort)
    while not abort():
        ...

This produces an error.

    AttributeError: 'bool' object has no attribute '_build_request'

**Comment by djungelorm** [comment]
Yes that's possible, although the syntax is admittedly a little odd:

```
abort = conn.add_stream(getattr, vessel.control, 'abort')
while not abort():
    ...
```

**Comment by janismac** [comment]
Thanks! Maybe you could add it to the docs. Here:

http://djungelorm.github.io/krpc/docs/python/client.html#streaming-data-from-the-server

**Comment by djungelorm** [comment]
Will do!
