### ISSUE TITLE
C# Client

### ISSUE THREAD

**Issue by pchcku** [djungelorm/krpc#178]
This would open up a lot of amazing possibilities, for example WPF GUIs and such.

Since setting up a working build environment is quite a hassle for Windows users, maybe distribute it as a nuget package, Or at least as a pre-built class library?

**Comment by djungelorm** [comment]
Yeah I agree this would be very useful. It's high on my todo list.

I think distributing a class library via nuget is the way to go.

**Comment by artwhaley** [comment]
I know that putting eta's on hobby projects is always dangerous...  but do you have any guesstimate on when you think this might happen?  I've been working on a gui interface in pyQT...  and I haven't just been THRILLED  with this as a cross platform solution...  and I'm having to teach myself python as I go.  I'd love to be able to switch over to mono...  if the c# client is planned for the first half of the year, I'd wait...  if it's probably not coming until much later...  I'll keep going with python!  And... I totally understand that any guess is just that, a guess and that things change!

**Comment by djungelorm** [comment]
This isn't a firm commitment (obviously :P) but I'm sure it's be done way before the middle of the year!

I've had a go at hacking together a simple prototype - and it works. Most of the difficulty in implementing new clients is learning the language (if I don't already know it, as was the case with lua) and figuring out how to do the protobuf decoding/encoding. I know C# and have already figured out the protobuf stuff for the server code, so coding up a client should be fairly easy.

**Comment by djungelorm** [comment]
Quick update: I've got a C# client working nicely :)

I'll hopefully commit and release it over the weekend.

**Comment by pchcku** [comment]
That's fantastic news. Did you have any success with making it available as nuget?

**Comment by djungelorm** [comment]
Yes it will be added to nuget soon.

**Comment by djungelorm** [comment]
Available here: https://www.nuget.org/packages/KRPC.Client

Note: the package had to be marked as "pre-release" as it depends on Google.Protobuf 3.0.0-beta3. Although I've testing it quite thoroughly so it should be reasonably stable.
