### ISSUE TITLE
Little Documentation Bug

### ISSUE THREAD

**Issue by artwhaley** [djungelorm/krpc#181]
The example on the 'Interacting with Parts' portion of the documentation shows:

import krpc
conn = krpc.connect()
vessel = conn.space_center.active_vessel

ports = vessel.parts.docking_ports
port = list(filter(lambda p: p.part.title == 'Clamp-O-Tron Docking Port', ports))[0]
vessel.parts.controlling = port

But it seems that vessel.parts.controlling needs to be a part?  Should the last line be:

vessel.parts.controlling = port.part

?

**Comment by djungelorm** [comment]
Confirmed - it's a bug.

```TypeError: SpaceCenter.Parts_set_Controlling() argument 1 must be a <class 'krpc.types.Part'>, got a <class 'krpc.types.DockingPort'>```
