### ISSUE TITLE
Base classes are not directly accessible in the python API

### ISSUE THREAD

**Issue by rakslice** [djungelorm/krpc#183]
It's awkward to use the enums from Python, since the base classes are not accessible (at least not at the names given by their repr(), for instance 'krpc.service.SpaceCenter' for SpaceCenter) except by going through an object instance.  Would it be possible to make them accessible? Judging by the repr() it seems like decisions about where to put them have already been made. =)

**Comment by djungelorm** [comment]
The enum base classes are accessible through the connection object (the classes for them are dynamically created when you connect to the server, so they have to be accessed through the connection object).

For example:
```python
conn = krpc.connect()
sit = conn.space_center.active_vessel.situation
print s
print type(s)
print conn.space_center.VesselSituation
```
The last two lines print out the same thing: ```<enum 'VesselSituation'>```
The last line shows where the enum type is stored for VesselSituation defined in the SpaceCenter service.
