### ISSUE TITLE
vessel angular velocity info for pitch/roll/yaw automation

### ISSUE THREAD

**Issue by rakslice** [djungelorm/krpc#184]
My apologies, I suspect I'm missing something obvious, so this is more of a support request than a feature issue. 

Is it possible to get the angular velocity of a vessel with respect to its orientation (direction and up axes)? If I use `Vessel.angular_velocity` with `Vessel.reference_frame`, I get basically 0 (presumably because the reference frame is rotating with the vessel) and I can't figure out how to transform `angular_velocity` I get for an outside frame of reference (for instance `CelestialBody.non_rotating_reference_frame`) based on the direction of the spacecraft to get an angular velocity that is pretty constant over time when the vessel is rotating at a constant rate.

My goal is to automate orientation control for docking purposes, and I'm writing code to control pitch/roll/yaw inputs directly, as SAS with maneuver nodes wobbles like crazy and the autopilot overshoots so far it doesn't even converge sometimes.

**Comment by djungelorm** [comment]
Vessel.reference_frame does indeed rotate with the vessel so you'll get zero for angular velocity.

I think the best way to do it is to get the angular velocity using the celestial body non-rotating reference frame, then convert it to the vessel's direction axes.

There are a static methods in the spacecenter service to transform positions/velocities etc. between reference frames here:
http://djungelorm.github.io/krpc/docs/python/api/space-center/space-center.html#SpaceCenter.SpaceCenter.transform_direction

If you use the SpaceCenter.transform_direction method that will modify the direction of the angular velocity vector to the correct axes, without modifying its magnitude. For example:

```python
body_ref_frame = vessel.orbit.body.non_rotating_reference_frame
angvel = vessel.angular_velocity(body_ref_frame)
spacecenter.transform_direction(angvel, body_ref_frame, vessel.reference_frame)
```
