### ISSUE TITLE
Position of terrain at given latitude/longitude

### ISSUE THREAD

**Issue by goncalopp** [djungelorm/krpc#186]
Is there a way to determine this? Usecase is landing on a specific place.

I realize there's `CelestialBody.equatorial_radius` and `CelestialBody.direction`, so you can work out the position at "sea level", but the height is missing. 

`Flight.elevation` is not enough if not landing vertically.

**Comment by djungelorm** [comment]
Currently the only way to measure terrain height is to have a vessel above the location.

Could add a method to the CelestialBody class to return the terrain height at a given latitude and longitude?

**Comment by goncalopp** [comment]
Getting the position tuple would be easier (for the user), but terrain height is enough given additional work on the client side

**Comment by djungelorm** [comment]
Ah yes that would be useful. Will add methods for both height and position (in some chosen reference frame).

**Comment by djungelorm** [comment]
https://github.com/S-C-A-N/SCANsat/blob/release/SCANsat/SCANutil.cs#L282
