### ISSUE TITLE
Vessel properties

### ISSUE THREAD

**Issue by astrofrog** [djungelorm/krpc#82]
In the unit tests for the Python code, there is a reference to things like ``vessel.mass`` and ``vessel.cross_sectional_area``. However, I don't see these even with the example craft provided. Is this functionality that doesn't yet exist, or that was removed for any reason? I would like to be able to know which parts are in each stage, to compute e.g. the total mass of the ship and thrust of each stage, in order to compute orbits.

**Comment by djungelorm** [comment]
That functionality doesn't exist in 0.1.3. vessel.mass and vessel.cross_sectional_area have been implemented, and will be part of version 0.1.4. The functionality to compute masses of stages and do things with parts is high up on the todo list! (#46)
