### ISSUE TITLE
autopilot error 90 degrees off?

### ISSUE THREAD

**Issue by borogove** [djungelorm/krpc#98]
I'm seeing the vessel.auto_pilot.error term holding around 90 degrees when I'm on the requested and expected orientation, using set_direction( ..., self.orbit.body.reference_frame ) instead of the expected near-zero error. Disagreement about frame of reference?

**Comment by djungelorm** [comment]
Confirmed. It's an issue with the roll being included in the error (even if a roll wasn't requested).

I'm going to split it into two properties:
* Error - the angle between the current vessel direction and the requested direction
* RollError - the difference between the current and target rolls, and 0 if no roll was requested
